compaction: Fix namespace for several exceptions names
PR #26214 clashed with #25828 -- the former was branched before the
latter was merged, they do not conflict (in code), but the latter fails
to compile because of the change in former:

    compaction/compaction.cc:1638:23: error: use of undeclared identifier 'compaction_aborted_exception'; did you mean 'sstables::compaction_aborted_exception'?
     1638 |                 throw compaction_aborted_exception(
          |                       ^
    ./sstables/exceptions.hh:70:7: note: 'sstables::compaction_aborted_exception' declared here
       70 | class compaction_aborted_exception : public compaction_job_exception {
          |       ^
    compaction/compaction.cc:1733:32: error: unknown type name 'malformed_sstable_exception'; did you mean 'sstables::malformed_sstable_exception'?
     1733 |                 } catch (const malformed_sstable_exception& e) {
          |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
          |                                sstables::malformed_sstable_exception
    ./sstables/exceptions.hh:19:7: note: 'sstables::malformed_sstable_exception' declared here
       19 | class malformed_sstable_exception : public std::exception {
          |       ^
    2 errors generated.

Signed-off-by: Pavel Emelyanov <xemul@scylladb.com>