aws_error: Add factory method for `aws_error` from exception
Move `aws_error` creation logic out of `retryable_http_client` and
into the `aws_error` class to support reuse across components.

(cherry picked from commit d53095d72f9eda615466695d84abff7ad06398a7)