test: topology: conftest.py: fix name collision between function parameter and import
`mypy` complains:
```
error: "Literal[True]" has no attribute "SSLContext"
```
on this piece:
```
ssl.SSLContext
```

That's because `ssl` was a parameter to the function of type `bool`
which overshadows the `ssl` module import.