locator: Add missing file.hh include in production_snitch_base
```
clang++

build/dev/locator/production_snitch_base.o
locator/production_snitch_base.cc
In file included from locator/production_snitch_base.cc:41:
In file included from ./locator/production_snitch_base.hh:41:
In file included from
/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/unordered_map:38:
/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/type_traits:1329:23:
error: incomplete type 'seastar::file' used in type trait expression
                    __bool_constant<__has_trivial_destructor(_Tp)>>
		                                        ^
```

This code compiles now due to indirect include from repair.hh.