trigger_ci.yaml: fix checkout failure
The action failed with
```
  /usr/bin/git branch --list --remote origin/debug-trigger-ci
  /usr/bin/git tag --list debug-trigger-ci
  Error: A branch or tag with the name 'debug-trigger-ci' could not be found

```

Fixing it, verified locally using `act` tool, but real verification need to be after this will be merged due to the tool limitaion