auth: Remove unused client member variables from authenticator classes
GCC warned that `password_authenticator::_group0_client` and
`standard_role_manager::_group0_client` are unused throughout the codebase.

This commit:
- Removes both redundant member variables
- Eliminates associated parameters from function signatures in their
  respective initialization call chains
- Simplifies related code paths in both classes

These changes reduce code complexity and resolve static analyzer warnings
without affecting functionality.

The warning from GCC looks like:
```
FAILED: auth/CMakeFiles/scylla_auth.dir/RelWithDebInfo/password_authenticator.cc.o
/home/kefu/.local/bin/clang++ -DSCYLLA_BUILD_MODE=release -DXXH_PRIVATE_API -DCMAKE_INTDIR=\"RelWithDebInfo\" -I/home/kefu/dev/scylladb -I/home/kefu/dev/scylladb/build -I/home/kefu/dev/scylladb/build/gen -isystem /home/kefu/dev/scylladb/seastar/include -isystem /home/kefu/dev/scylladb/build/RelWithDebInfo/seastar/gen/include -isystem /home/kefu/dev/scylladb/abseil -isystem /home/kefu/dev/scylladb/build/rust -I/usr/include/p11-kit-1 -ffunction-sections -fdata-sections -O3 -g -gz -std=gnu++23 -fvisibility=hidden -Wall -Werror -Wextra -Wno-error=deprecated-declarations -Wimplicit-fallthrough -Wno-c++11-narrowing -Wno-deprecated-copy -Wno-mismatched-tags -Wno-missing-field-initializers -Wno-overloaded-virtual -Wno-unsupported-friend -Wno-unused-parameter -ffile-prefix-map=/home/kefu/dev/scylladb/= -ffile-prefix-map=/home/kefu/dev/scylladb/build=. -ffile-prefix-map=/home/kefu/dev/scylladb/build/=build -march=westmere -mllvm -inline-threshold=2500 -fno-slp-vectorize -std=gnu++23 -Werror=unused-result -DSEASTAR_API_LEVEL=7 -DSEASTAR_SSTRING -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_SCHEDULING_GROUPS_COUNT=19 -DSEASTAR_LOGGER_TYPE_STDOUT -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_THREAD_NO_LIB -DBOOST_THREAD_DYN_LINK -DFMT_SHARED -MD -MT auth/CMakeFiles/scylla_auth.dir/RelWithDebInfo/password_authenticator.cc.o -MF auth/CMakeFiles/scylla_auth.dir/RelWithDebInfo/password_authenticator.cc.o.d -o auth/CMakeFiles/scylla_auth.dir/RelWithDebInfo/password_authenticator.cc.o -c /home/kefu/dev/scylladb/auth/password_authenticator.cc
In file included from /home/kefu/dev/scylladb/auth/password_authenticator.cc:11:
/home/kefu/dev/scylladb/auth/password_authenticator.hh:40:36: error: private field '_group0_client' is not used [-Werror,-Wunused-private-field]
   40 |     ::service::raft_group0_client& _group0_client;
      |                                    ^
1 error generated.
```

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>