test: add type annotations where `mypy` complains
`mypy` complains when global variables are used without types, e.g.:
```
run_with_temporary_dir_pids = set()
```

gives:
```
error: Need type annotation for "run_with_temporary_dir_pids" (hint:
"run_with_temporary_dir_pids: Set[<type>] = ...")
```

Fix those errors.