repair: Remove all row level repair during shtudown
We saw dtest failed to stop a node like:

```
ERROR: repair_one_missing_row_test (repair_additional_test.RepairAdditionalTest)
----------------------------------------------------------------------
Traceback (most recent
[2019.1.3.node1.repair.zip](https://github.com/scylladb/scylla/files/2723244/2019.1.3.node1.repair.zip)
 call last):
  File "/home/asias/src/cloudius-systems/scylla-dtest/repair_additional_test.py", line 2521, in repair_one_missing_row_test
    return RepairAdditionalBase._repair_one_missing_row_test(self)
  File "/home/asias/src/cloudius-systems/scylla-dtest/repair_additional_test.py", line 1842, in _repair_one_missing_row_test
    self.check_rows_on_node(node2, nr_rows)
  File "/home/asias/src/cloudius-systems/scylla-dtest/repair_additional_test.py", line 34, in check_rows_on_node
    node.stop(wait_other_notice=True)
  File "/home/asias/src/cloudius-systems/scylla-ccm/ccmlib/scylla_node.py", line 496, in stop
    raise NodeError("Problem stopping node %s" % self.name)
NodeError: Problem stopping node node1
```

The problem is:

1) repair_meat is created
repair_meta -> repair_writer::create_writer() -> t.stream_in_progress()
repari_meta -> repair_reader::repair_reader -> cf.read_in_progress()

2) repair_meta is stored in _repair_metas map.

3) Shtudown repair, repair_meta is not removed from the _repair_metas map

4) Shutdown database which wait for the utils::phased_barrier.

To fix, we should stop and remove all the repair_meata from the _repair_metas map.

Tests: 30 successful runs of the repair_kill_2_test

Fixes: #4044