build: cmake: remove "#pragma  once" as well
in check_headers.cmake, we remove the `#pragma once` directive in
the header to be checked, so the compiler does not fail with the
error like:

```
error: #pragma once in main file [-Werror,-Wpragma-once-outside-header]
```

but there are chances we have multiple spaces between `#pragma` and
`once`. this is also a valid `#pragma` directive. so let's be more
tolerant and detect this case as well.

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>