utils: to_string: drop formatter for pair<> and map<>
the one for pair<> does not work with the formatter for range-alike containers provided
by {fmt}:

```
/usr/include/fmt/ranges.h:555:30: error: no member named 'set_brackets' in 'fmt::detail::fallback_formatter<std::pair<const seastar::basic_sstring<signed char, unsigned int, 31, false>, std::vector<std::vector<std::optional<seastar::basic_sstring<signed char, unsigned int, 31, false>>>>>>'
      underlying_.underlying().set_brackets({}, {});
      ~~~~~~~~~~~~~~~~~~~~~~~~ ^
```

and the one for map<> does not work if the one for pair<> is missing.
so drop both of them.

Refs #13245

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>