scylla-gdb.py: coding style fixes
scylla-gdb.py:1:11: E401 multiple imports on one line
scylla-gdb.py:5:1: F811 redefinition of unused 're' from line 2
scylla-gdb.py:10:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:19:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:24:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:30:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:39:9: E722 do not use bare 'except'
scylla-gdb.py:47:33: E711 comparison to None should be 'if cond is None:'
scylla-gdb.py:63:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:90:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:115:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:139:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:161:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:184:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:204:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:210:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:214:5: E301 expected 1 blank line, found 0
scylla-gdb.py:221:5: E301 expected 1 blank line, found 0
scylla-gdb.py:224:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:252:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:267:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:284:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:300:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:314:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:318:5: E301 expected 1 blank line, found 0
scylla-gdb.py:322:5: E301 expected 1 blank line, found 0
scylla-gdb.py:337:1: E305 expected 2 blank lines after class or function
definition, found 1
scylla-gdb.py:339:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:342:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:345:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:348:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:352:129: E202 whitespace before ')'
scylla-gdb.py:361:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:363:129: E202 whitespace before ')'
scylla-gdb.py:371:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:375:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:378:5: E301 expected 1 blank line, found 0
scylla-gdb.py:383:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:386:5: E301 expected 1 blank line, found 0
scylla-gdb.py:393:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:396:5: E301 expected 1 blank line, found 0
scylla-gdb.py:407:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:410:5: E301 expected 1 blank line, found 0
scylla-gdb.py:412:9: E306 expected 1 blank line before a nested definition,
found 0
scylla-gdb.py:439:26: E703 statement ends with a semicolon
scylla-gdb.py:462:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:500:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:506:5: E722 do not use bare 'except'
scylla-gdb.py:516:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:518:18: E271 multiple spaces after keyword
scylla-gdb.py:522:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:530:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:533:5: E301 expected 1 blank line, found 0
scylla-gdb.py:537:13: E306 expected 1 blank line before a nested definition,
found 0
scylla-gdb.py:547:9: E722 do not use bare 'except'
scylla-gdb.py:550:26: E261 at least two spaces before inline comment
scylla-gdb.py:568:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:571:5: E301 expected 1 blank line, found 0
scylla-gdb.py:577:13: E128 continuation line under-indented for visual indent
scylla-gdb.py:577:39: E226 missing whitespace around arithmetic operator
scylla-gdb.py:583:15: E128 continuation line under-indented for visual indent
scylla-gdb.py:596:19: E128 continuation line under-indented for visual indent
scylla-gdb.py:609:82: E227 missing whitespace around bitwise or shift operator
scylla-gdb.py:609:90: E226 missing whitespace around arithmetic operator
scylla-gdb.py:609:113: E226 missing whitespace around arithmetic operator
scylla-gdb.py:613:1: E303 too many blank lines (3)
scylla-gdb.py:645:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:659:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:671:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:678:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:679:9: E128 continuation line under-indented for visual indent
scylla-gdb.py:680:9: E128 continuation line under-indented for visual indent
scylla-gdb.py:681:9: E128 continuation line under-indented for visual indent
scylla-gdb.py:682:9: E128 continuation line under-indented for visual indent
scylla-gdb.py:708:12: E111 indentation is not a multiple of four
scylla-gdb.py:721:13: E128 continuation line under-indented for visual indent
scylla-gdb.py:723:13: E128 continuation line under-indented for visual indent
scylla-gdb.py:725:13: E128 continuation line under-indented for visual indent
scylla-gdb.py:727:13: E128 continuation line under-indented for visual indent
scylla-gdb.py:729:13: E128 continuation line under-indented for visual indent
scylla-gdb.py:748:33: E261 at least two spaces before inline comment
scylla-gdb.py:770:17: E306 expected 1 blank line before a nested definition,
found 0
scylla-gdb.py:795:17: E128 continuation line under-indented for visual indent
scylla-gdb.py:796:17: E128 continuation line under-indented for visual indent
scylla-gdb.py:797:17: E128 continuation line under-indented for visual indent
scylla-gdb.py:798:17: E128 continuation line under-indented for visual indent
scylla-gdb.py:800:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:807:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:814:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:820:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:823:5: E301 expected 1 blank line, found 0
scylla-gdb.py:845:35: E703 statement ends with a semicolon
scylla-gdb.py:865:91: E703 statement ends with a semicolon
scylla-gdb.py:896:9: F841 local variable 'segment_size' is assigned to but
never used
scylla-gdb.py:904:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:907:5: E301 expected 1 blank line, found 0
scylla-gdb.py:915:73: E128 continuation line under-indented for visual indent
scylla-gdb.py:916:73: E128 continuation line under-indented for visual indent
scylla-gdb.py:917:73: E126 continuation line over-indented for hanging indent
scylla-gdb.py:922:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:925:5: E301 expected 1 blank line, found 0
scylla-gdb.py:933:13: E128 continuation line under-indented for visual indent
scylla-gdb.py:934:13: E128 continuation line under-indented for visual indent
scylla-gdb.py:934:49: E251 unexpected spaces around keyword / parameter equals
scylla-gdb.py:934:51: E251 unexpected spaces around keyword / parameter equals
scylla-gdb.py:934:74: E251 unexpected spaces around keyword / parameter equals
scylla-gdb.py:934:76: E251 unexpected spaces around keyword / parameter equals
scylla-gdb.py:940:13: E128 continuation line under-indented for visual indent
scylla-gdb.py:941:13: E128 continuation line under-indented for visual indent
scylla-gdb.py:949:17: E128 continuation line under-indented for visual indent
scylla-gdb.py:950:17: E128 continuation line under-indented for visual indent
scylla-gdb.py:951:17: E128 continuation line under-indented for visual indent
scylla-gdb.py:952:21: E128 continuation line under-indented for visual indent
scylla-gdb.py:953:21: E128 continuation line under-indented for visual indent
scylla-gdb.py:954:21: E128 continuation line under-indented for visual indent
scylla-gdb.py:955:21: E128 continuation line under-indented for visual indent
scylla-gdb.py:958:1: E305 expected 2 blank lines after class or function
definition, found 1
scylla-gdb.py:958:11: E261 at least two spaces before inline comment
scylla-gdb.py:959:1: E302 expected 2 blank lines, found 0
scylla-gdb.py:971:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:989:5: E301 expected 1 blank line, found 0
scylla-gdb.py:993:5: E301 expected 1 blank line, found 0
scylla-gdb.py:995:5: E301 expected 1 blank line, found 0
scylla-gdb.py:997:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1001:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1005:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1029:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1034:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1037:46: E128 continuation line under-indented for visual indent
scylla-gdb.py:1057:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1060:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1071:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1076:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1084:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1093:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1096:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1101:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1104:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1116:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1119:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1123:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1126:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1132:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1135:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1138:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1141:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1147:15: E241 multiple spaces after ':'
scylla-gdb.py:1148:15: E241 multiple spaces after ':'
scylla-gdb.py:1149:15: E241 multiple spaces after ':'
scylla-gdb.py:1150:15: E241 multiple spaces after ':'
scylla-gdb.py:1151:15: E241 multiple spaces after ':'
scylla-gdb.py:1152:15: E241 multiple spaces after ':'
scylla-gdb.py:1153:15: E241 multiple spaces after ':'
scylla-gdb.py:1154:15: E241 multiple spaces after ':'
scylla-gdb.py:1170:20: E221 multiple spaces before operator
scylla-gdb.py:1191:40: E226 missing whitespace around arithmetic operator
scylla-gdb.py:1191:59: E226 missing whitespace around arithmetic operator
scylla-gdb.py:1225:1: E305 expected 2 blank lines after class or function
definition, found 1
scylla-gdb.py:1227:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1233:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1236:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1240:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1278:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1281:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1284:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1287:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1293:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1296:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1320:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1323:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1355:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1362:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1383:1: E302 expected 2 blank lines, found 1
scylla-gdb.py:1386:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1388:9: E306 expected 1 blank line before a nested definition,
found 0
scylla-gdb.py:1397:13: F841 local variable 'selector' is assigned to but never
used
scylla-gdb.py:1446:5: E301 expected 1 blank line, found 0
scylla-gdb.py:1477:5: E301 expected 1 blank line, found 0

Signed-off-by: Alexys Jacob <ultrabug@gentoo.org>
Message-Id: <20181104113603.1111-1-ultrabug@gentoo.org>