test: topology: wait_for_token_ring_and_group0_consistency: per-server timeout
The function is currently flaky, especially in debug mode,
since it is given a single deadline for matching the
group0 config vs. token_ring_host_ids on all servers in the
cluster.

Instead, define a timeout of 30 seconds by default,
but applied for each server.

See for example https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2928/artifact/testlog/x86_64/debug/topology.test_replace.3.log
```
09:20:50.423 INFO> Group 0 members by Server(352, 127.248.218.41): {('831964b5-ea26-4e41-b380-6b4ae52d08fa', True), ('a842b1fe-a263-4ea2-85af-7e61bc1d712b', True), ('d9535651-692a-476b-96ba-7ba0da59de0c', True), ('cdaf1f9f-b26b-432e-87e6-b57db9860506', True)}
09:20:50.423 DEBUG> RESTClient fetching GET http://127.248.218.41:10000/storage_service/tokens_endpoint
09:20:50.426 INFO> Normal endpoints' IPs by Server(352, 127.248.218.41): {'127.248.218.12', '127.248.218.22', '127.248.218.41'}
09:20:50.426 DEBUG> RESTClient fetching GET http://127.248.218.41:10000/storage_service/host_id
09:20:50.427 INFO> All host IDs by Server(352, 127.248.218.41): {'831964b5-ea26-4e41-b380-6b4ae52d08fa', 'a842b1fe-a263-4ea2-85af-7e61bc1d712b', 'd9535651-692a-476b-96ba-7ba0da59de0c'}
09:20:50.427 INFO> Normal endpoints' host IDs by Server(352, 127.248.218.41): {'831964b5-ea26-4e41-b380-6b4ae52d08fa', 'a842b1fe-a263-4ea2-85af-7e61bc1d712b', 'd9535651-692a-476b-96ba-7ba0da59de0c'}
09:20:50.427 WARNING> Group 0 members and token ring members don't yet match according to Server(352, 127.248.218.41), symmetric difference: {'cdaf1f9f-b26b-432e-87e6-b57db9860506'}
...
09:21:19.927 WARNING> Group 0 members and token ring members don't yet match according to Server(352, 127.248.218.41), symmetric difference: {'cdaf1f9f-b26b-432e-87e6-b57db9860506'}
---------------------------- Captured log teardown -----------------------------
09:21:20.449 DEBUG> after_test for test_replace_different_ip_using_host_id (success: False)
09:21:20.449 DEBUG> RESTClient fetching GET http+unix://api/cluster/after-test/False
09:21:20.475 INFO> Cluster after test test_replace_different_ip_using_host_id: ScyllaCluster(name: a13d62e0-35b3-11ee-b749-a8a159ead561, running: ScyllaServer(352, 127.248.218.41, 831964b5-ea26-4e41-b380-6b4ae52d08fa), ScyllaServer(355, 127.248.218.12, d9535651-692a-476b-96ba-7ba0da59de0c), ScyllaServer(368, 127.248.218.22, a842b1fe-a263-4ea2-85af-7e61bc1d712b), stopped: ScyllaServer(348, 127.248.218.30, cdaf1f9f-b26b-432e-87e6-b57db9860506))
- generated xml file: /jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/xml/topology.test_replace.3.xunit.xml -
=========================== short test summary info ============================
FAILED test/topology/test_replace.py::test_replace_different_ip_using_host_id
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>